# Generated by Django 3.2.4 on 2021-06-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ahmad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='comlete',
            new_name='complete',
        ),
    ]
